// Generated by CoffeeScript 1.3.3

$(function() {
  var canvas,
    _this = this;
  canvas = new CanvasImages();
  canvas.setCssAbsolute();
  $("#add").bind("click", function() {
    return canvas.inImage("static/img/test.png");
  });
  return $('#save').bind("click", function() {
    return canvas.savePng();
  });
});
