// Generated by CoffeeScript 1.3.3
var BirthDrawing,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BirthDrawing = (function(_super) {

  __extends(BirthDrawing, _super);

  function BirthDrawing() {
    return BirthDrawing.__super__.constructor.apply(this, arguments);
  }

  BirthDrawing.prototype.makeUrl = function() {
    var collaboratorId, planId,
      _this = this;
    planId = "";
    collaboratorId = "";
    $.ajax({
      url: "/get_plan",
      method: "GET",
      async: false,
      success: function(res) {
        return planId = res.Plan.id;
      }
    });
    $.ajax({
      url: "/get_user",
      method: "GET",
      async: false,
      success: function(res) {
        return collaboratorId = res.User.id;
      }
    });
    return "/plan/" + planId + "/collaborator/" + collaboratorId("/photo");
  };

  return BirthDrawing;

})(Drawing);
