// Generated by CoffeeScript 1.3.3
var Connect, debug;

debug = true;

Connect = (function() {

  function Connect() {
    this.data = new ClassList();
  }

  Connect.prototype.get = function(url) {
    var res;
    if (debug) {
      res = {
        "User": {
          "id": "1",
          "username": "imausr",
          "fb_picture": "https:\/\/fbcdn-profile-a.akamaihd.net\/hprofile-ak-ash2\/368785_100000588696676_2051595305_q.jpg"
        }
      };
      ({
        "Plan": {
          "id": "1",
          "from_id": "1",
          "to_id": null,
          "memo": null,
          "created": null,
          "modified": null
        }
      });
      return this.getSuccess(res);
    } else {
      return $.ajax({
        type: "GET",
        url: url,
        dataType: "json",
        success: this.getSuccess
      });
    }
  };

  Connect.prototype.getSuccess = function(res) {
    var _this = this;
    if (res.Owner) {
      $("." + (owner - rihgt)).bind('click', function() {
        return _this.getFriends();
      });
      return view.updateOwner(res);
    } else if (res.Plan) {
      return view.updatePlan(res);
    } else if (res.collaborators) {
      return view.updateCollaborators(res);
    } else {
      if (res.Plan) {
        this.get("/get_collaborators");
      }
      if (res.Friend) {
        $("." + (select - user)).bind('click', function() {
          return _this.insertPlan();
        });
        return $('#content').html = this.setHtml(res);
      }
    }
  };

  Connect.prototype.setHtml = function(res) {
    var key, text, value;
    text = '<div class="select-friend">';
    for (key in res) {
      value = res[key];
      text += "<ul>";
      text += "<li class='friend-img'>";
      text += "<img src=" + value.fb_profile + ">";
      text += "</li>";
      text += "<li class='friend-name'>";
      text += "" + value.username;
      text += "</li>";
      text += "</ul>";
    }
    text += '</div>';
    return text;
  };

  Connect.prototype.getFriends = function() {
    return connect.get('/get_friends');
  };

  Connect.prototype.insertPlan = function() {
    return this.post("/insertPlan", {
      to_id: "",
      fb_picture: "",
      username: ""
    });
  };

  Connect.prototype.post = function(url, data) {
    return $.ajax({
      url: url,
      type: "POST",
      data: data,
      dataType: "json",
      success: this.postSuccess,
      error: this.postError
    });
  };

  Connect.prototype.postSuccess = function(res) {};

  Connect.prototype.postError = function(res) {};

  Connect.prototype.sendButtonClick = function() {
    return this.contributor("http://yahoo.co.jp");
  };

  Connect.prototype.contributor = function(url) {
    return location.href = url;
  };

  return Connect;

})();
