// Generated by CoffeeScript 1.3.3
var FriendsTable,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

FriendsTable = (function(_super) {

  __extends(FriendsTable, _super);

  FriendsTable.prototype.getUrl = "/get_friends";

  FriendsTable.prototype.postUrl = "/insert_plan";

  function FriendsTable(saveLocation) {
    this.postSuccess = __bind(this.postSuccess, this);
    FriendsTable.__super__.constructor.call(this, saveLocation);
    this.AjaxGet("friend");
  }

  FriendsTable.prototype.getSuccess = function(res) {
    var friend, _i, _len, _ref;
    this.data = res.Friend;
    this.viewParams = [
      {
        tplSelector: "#selectFriendTpl",
        appendSelector: ".main_contents"
      }
    ];
    _ref = this.data;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      friend = _ref[_i];
      this.viewParams.push({
        tplSelector: "#friendInfoTpl",
        appendSelector: ".main_contents .select-friend",
        data: friend
      });
    }
    view["delete"]('.main_contents > *');
    return this.viewUpdate();
  };

  FriendsTable.prototype.setEvents = function() {
    var friendInfo, selector, self;
    selector = ".main_contents .friend-info";
    friendInfo = this.data;
    self = this;
    return $(selector).click(function() {
      var index;
      index = $(selector).index(this);
      view["delete"]('.main_contents > *');
      return self.AjaxPost(friendInfo[index]);
    });
  };

  FriendsTable.prototype.postSuccess = function(res) {
    var _this = this;
    if (res.Success === "true") {
      this.AjaxPost({}, "/post/post_fb_timeline", function() {
        return alert("成功");
      });
      return location.href = '/mypage';
    } else {
      return view.update({
        tplSelector: "#insertPlanErrorTpl",
        appendSelector: ".main_contents"
      });
    }
  };

  return FriendsTable;

})(DataTable);
