// Generated by CoffeeScript 1.3.3

require(["vendor/jquery", "debug", "View", "dataTable", "UserTable", "PlanTable", "FriendsTable", "CollaboratorTable", "lib/underscore-min"], function() {
  window.dataTable = {};
  dataTable.userTable = new UserTable(dataTable);
  return dataTable.planTable = new PlanTable(dataTable);
});
