// Generated by CoffeeScript 1.3.3

require(["jquery", "debug", "View", "DataTable", "UserTable", "PlanTable", "FriendsTable", "CollaboratorTable", "lib/underscore-min"], function() {
  window.dataTable = {};
  return $(function() {
    dataTable.userTable = new UserTable(dataTable);
    return dataTable.planTable = new PlanTable(dataTable);
  });
});
