// Generated by CoffeeScript 1.3.3

require(["vendor/jquery", "debug", "View", "DataTable", "lib/underscore-min"], function() {
  return require(["UserTable", "PlanTable", "FriendsTable", "CollaboratorTable"], function() {
    window.dataTable = {};
    dataTable.userTable = new UserTable(dataTable);
    return dataTable.planTable = new PlanTable(dataTable);
  });
});
