// Generated by CoffeeScript 1.3.3
var PlanTable,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PlanTable = (function(_super) {

  __extends(PlanTable, _super);

  PlanTable.prototype.getUrl = "/get_plans";

  function PlanTable(saveLocation) {
    PlanTable.__super__.constructor.call(this, saveLocation);
    this.AjaxGet("plan");
  }

  PlanTable.prototype.getSuccess = function(res) {
    this.data = {
      "Plans": res
    };
    console.log("data");
    console.log(this.data);
    this.viewParams = [
      {
        tplSelector: "#cardTpl",
        appendSelector: '.main_contents',
        method: "appendTo"
      }, {
        tplSelector: "#planTpl",
        appendSelector: '.main_contents .card-left',
        method: "appendTo",
        data: this.data
      }
    ];
    if (debug.alertflag) {
      alert("processing");
    }
    if (debug.flag) {
      console.log("in owner");
    }
    if (debug.flag) {
      console.log(res);
    }
    this.viewUpdate();
    return this.saveLocation.collaborators = new CollaboratorTable(this.saveLocation);
  };

  PlanTable.prototype.setEvents = function() {
    var self;
    self = this;
    return $(".send-btn").click(function() {
      var index, plan;
      index = $(".send-btn").index(this);
      plan = self.data.Plans[index];
      return location.href = "/plan/" + plan.id + "/post/confirm";
    });
  };

  return PlanTable;

})(DataTable);
