// Generated by CoffeeScript 1.3.3
var UserTable,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

UserTable = (function(_super) {

  __extends(UserTable, _super);

  UserTable.prototype.getUrl = "/get_user";

  function UserTable(saveLocation) {
    UserTable.__super__.constructor.call(this, saveLocation);
    this.AjaxGet("user");
  }

  UserTable.prototype.getSuccess = function(res) {
    var _this = this;
    this.data = res;
    this.viewParams = [
      {
        tplSelector: "#ownerTpl",
        appendSelector: ".main_contents",
        method: "prependTo",
        data: this.data
      }
    ];
    if (debug.alertflag) {
      alert("processing");
    }
    if (debug.flag) {
      console.log("in owner");
    }
    if (debug.flag) {
      console.log(res);
    }
    this.viewUpdate();
    return $(".owner-right button").bind('click', function() {
      if (debug.flag) {
        console.log("call getFriends");
      }
      return _this.createFriends();
    });
  };

  UserTable.prototype.createFriends = function() {
    return this.saveLocation["friends"] = new FriendsTable(this.saveLocation);
  };

  return UserTable;

})(DataTable);
