// Generated by CoffeeScript 1.3.3
var View;

View = (function() {

  function View() {
    ({
      update: function(params) {
        var content;
        if (params.data === void 0) {
          return $($(params.tplSelector).html()).appendTo(params.appendSelector);
        } else {
          content = _.template($(params.tplSelector).html(), params.data);
          switch (params.method) {
            case "appendTo":
              return $(content).appendTo(params.appendSelector);
            case "prependTo":
              return $(content).prependTo(params.appendSelector);
            default:
              return $(content).appendTo(params.appendSelector);
          }
        }
      },
      "delete": function(selector) {
        return $(selector).remove();
      }
    });
  }

  return View;

})();
