// Generated by CoffeeScript 1.3.3
var Component,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Component = (function() {

  function Component(src, type) {
    this.mouseup = __bind(this.mouseup, this);

    this.mouseout = __bind(this.mouseout, this);

    this.mousemove = __bind(this.mousemove, this);

    this.mousedown = __bind(this.mousedown, this);

    this.touchend = __bind(this.touchend, this);

    this.touchmove = __bind(this.touchmove, this);

    this.touchstart = __bind(this.touchstart, this);
    if (type === "img") {
      this.data = {
        top: 0,
        left: 0,
        width: 100,
        height: 100,
        priority: 1
      };
    }
  }

  Component.prototype.incrementPriority = function() {
    return this.data.priority += 1;
  };

  Component.prototype.setEvents = function(selector) {
    var func, key, that, _ref, _results;
    that = this;
    _ref = this.events;
    _results = [];
    for (key in _ref) {
      func = _ref[key];
      _results.push($(selector).bind(key, func));
    }
    return _results;
  };

  Component.prototype.touchstart = function() {
    this.clicking = true;
    return console.log(event);
  };

  Component.prototype.touchmove = function() {};

  Component.prototype.touchend = function() {
    return this.clicking = false;
  };

  Component.prototype.mousedown = function() {
    this.clicking = true;
    this.x = event.pageX;
    return this.y = event.pageY;
  };

  Component.prototype.mousemove = function() {
    var id;
    if (this.clicking) {
      id = event.target.id;
      $("#" + id).css({
        "top": "+=" + (event.pageY - this.y),
        "left": "+=" + (event.pageX - this.x)
      });
      this.x = event.pageX;
      return this.y = event.pageY;
    }
  };

  Component.prototype.mouseout = function() {
    return this.mouseup();
  };

  Component.prototype.mouseup = function() {
    return this.clicking = false;
  };

  return Component;

})();
