// Generated by CoffeeScript 1.3.3
var TextComponent;

TextComponent = (function() {

  function TextComponent(text, font) {
    this.text = text;
    this.font = font != null ? font : "bold 16px sans-serif";
  }

  TextComponent.prototype.rangeImageInCheck = function(point, coords, size) {
    if (coords == null) {
      coords = this.coords;
    }
    if (size == null) {
      size = this.size;
    }
    return false;
  };

  TextComponent.prototype.rangeFocusInCheck = function(point) {
    return false;
  };

  TextComponent.prototype.getfocus = function() {
    return false;
  };

  TextComponent.prototype.getWidth = function(ctx) {
    ctx.font = this.font;
    return ctx.measureText(this.text).width;
  };

  TextComponent.prototype.draw = function(ctx) {
    ctx.font = this.font;
    return ctx.fillText(this.text, this.left, this.top);
  };

  return TextComponent;

})();
