// Generated by CoffeeScript 1.3.3
var eventExCoords, offsetOn;

eventExCoords = function(event) {
  var coords;
  if (event.offsetX) {
    coords = {
      x: event.offsetX,
      y: event.offsetY
    };
  } else {
    coords = {
      x: event.pageX,
      y: event.pageY - 85
    };
  }
  return coords;
};

offsetOn = function($elm, event) {
  var coords;
  coords = {};
  coords.x = event.pageX - $elm.offset().left;
  coords.y = event.pageY - $elm.offset().top;
  return coords;
};
