// Generated by CoffeeScript 1.3.3

$(function() {
  var planid, url,
    _this = this;
  url = location.href;
  planid = url.substr(url.lastIndexOf('/') + 1);
  window.drawing = new BirthdayArrange(planid);
  console.log(drawing);
  drawing.setCssAbsolute();
  drawing.setImages();
  return $("#add").bind("click", function() {
    return drawing.inImage("static/img/test.png");
  });
});
