// Generated by CoffeeScript 1.3.3
var BirthdayDeco;

BirthdayDeco = (function() {

  function BirthdayDeco(planId) {
    this.planId = planId;
  }

  BirthdayDeco.prototype.load = function() {
    var d, self;
    self = this;
    d = $.Deferred();
    ($.ajax({
      url: "/plan/" + this.planId,
      method: "GET",
      dataType: "json"
    })).then(function(res) {
      if (!res) {
        alert('該当するPlanが存在しません');
        return;
      }
      self.plan = res.Plan;
      self.username = self.plan.username;
      self.profileImage = new Image();
      self.profileImage.onload = function() {
        return d.resolve();
      };
      self.profileImage.onerror = function(err) {
        return d.relect(err);
      };
      return self.profileImage.src = '/facebook/' + self.plan.to_id + '/picture';
    }, function(err) {
      return d.reject(err);
    });
    return d;
  };

  return BirthdayDeco;

})();
