// Generated by CoffeeScript 1.3.3
var eventExCoords;

eventExCoords = function(event) {
  var coords;
  if (event.offsetX) {
    coords = {
      x: event.offsetX,
      y: event.offsetY
    };
  } else {
    coords = {
      x: event.pageX,
      y: event.pageY - 85
    };
  }
  return coords;
};
